project_id = "dctapmbdsfmzhtbpgigc"

[functions.gateway-payment]
verify_jwt = false

[functions.send-appointment-notification]
verify_jwt = false

[functions.mercadopago-payment]
verify_jwt = false

[functions.validate-gateway]
verify_jwt = false
