project_id = "dctapmbdsfmzhtbpgigc"

[functions.gateway-payment]
verify_jwt = false

[functions.send-appointment-notification]
verify_jwt = false

[functions.mercadopago-payment]
verify_jwt = false

[functions.validate-gateway]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.send-appointment-reminders]
verify_jwt = false

[functions.ai-psi-analysis]
verify_jwt = false

[functions.create-appointment]
verify_jwt = false

[functions.get-client-appointment]
verify_jwt = false

[functions.metered-webhook]
verify_jwt = false

[functions.get-turn-credentials]
verify_jwt = false

[functions.domain-verification]
verify_jwt = false

[functions.cloudflare-dns-setup]
verify_jwt = false
